# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_autoPrt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoPrt(object):
    def setupUi(self, AutoPrt):
        AutoPrt.setObjectName("AutoPrt")
        AutoPrt.resize(1157, 940)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AutoPrt.sizePolicy().hasHeightForWidth())
        AutoPrt.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(AutoPrt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        AutoPrt.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AutoPrt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1157, 23))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        AutoPrt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AutoPrt)
        self.statusbar.setObjectName("statusbar")
        AutoPrt.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(AutoPrt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        AutoPrt.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actMultiConfig = QtWidgets.QAction(AutoPrt)
        self.actMultiConfig.setObjectName("actMultiConfig")
        self.actMultiTest = QtWidgets.QAction(AutoPrt)
        self.actMultiTest.setObjectName("actMultiTest")
        self.actPlatformConfig = QtWidgets.QAction(AutoPrt)
        self.actPlatformConfig.setObjectName("actPlatformConfig")
        self.actiontest = QtWidgets.QAction(AutoPrt)
        self.actiontest.setObjectName("actiontest")
        self.actionyuan = QtWidgets.QAction(AutoPrt)
        self.actionyuan.setObjectName("actionyuan")
        self.toolBar.addAction(self.actPlatformConfig)
        self.toolBar.addAction(self.actMultiConfig)
        self.toolBar.addAction(self.actMultiTest)

        self.retranslateUi(AutoPrt)
        QtCore.QMetaObject.connectSlotsByName(AutoPrt)

    def retranslateUi(self, AutoPrt):
        _translate = QtCore.QCoreApplication.translate
        AutoPrt.setWindowTitle(_translate("AutoPrt", "LS自动化工具"))
        self.toolBar.setWindowTitle(_translate("AutoPrt", "toolBar"))
        self.actMultiConfig.setText(_translate("AutoPrt", "配置"))
        self.actMultiTest.setText(_translate("AutoPrt", "测试"))
        self.actPlatformConfig.setText(_translate("AutoPrt", "平台配置"))
        self.actiontest.setText(_translate("AutoPrt", "示例配置"))
        self.actionyuan.setText(_translate("AutoPrt", "FTP配置"))
